name: Hello

logger:
  level: info
  file: app.log
  format: json

databases:
  mongos:
    sso_service:
      name: sso_service
      host: localhost
      port: 27017
      user: ""
      password: ""
      database: "sso_db"
  
SecretKey: "JWTSECRETKEY"